// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjjbCFnUq65sHie6xSVBeE6QsdaZlpxaI',
    appId: '1:835868961359:web:7ad2ea43a4c09a9049583a',
    messagingSenderId: '835868961359',
    projectId: 'society-complaint-app-86f2a',
    authDomain: 'society-complaint-app-86f2a.firebaseapp.com',
    storageBucket: 'society-complaint-app-86f2a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAJVC7k_GC1tH-Dy7cGQyn-CZZ5smFwzk',
    appId: '1:835868961359:android:dee1b8272799348e49583a',
    messagingSenderId: '835868961359',
    projectId: 'society-complaint-app-86f2a',
    storageBucket: 'society-complaint-app-86f2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXP_1EVro2a-Xqv0WAbWHaSxfLcCUcxlY',
    appId: '1:835868961359:ios:f95f437a1d46234149583a',
    messagingSenderId: '835868961359',
    projectId: 'society-complaint-app-86f2a',
    storageBucket: 'society-complaint-app-86f2a.firebasestorage.app',
    iosBundleId: 'com.example.societyComplaintApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXP_1EVro2a-Xqv0WAbWHaSxfLcCUcxlY',
    appId: '1:835868961359:ios:f95f437a1d46234149583a',
    messagingSenderId: '835868961359',
    projectId: 'society-complaint-app-86f2a',
    storageBucket: 'society-complaint-app-86f2a.firebasestorage.app',
    iosBundleId: 'com.example.societyComplaintApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjjbCFnUq65sHie6xSVBeE6QsdaZlpxaI',
    appId: '1:835868961359:web:a0c81530e8d5645e49583a',
    messagingSenderId: '835868961359',
    projectId: 'society-complaint-app-86f2a',
    authDomain: 'society-complaint-app-86f2a.firebaseapp.com',
    storageBucket: 'society-complaint-app-86f2a.firebasestorage.app',
  );
}
